
create table IF NOT EXISTS HOTEL_CONFIG (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  hotelName varchar(1000),
  address varchar(4000),
  city varchar (200),
  state varchar (2),
  country varchar (100),
  zip varchar(10),
  roomCount INTEGER,
  overbookingLevel FLOAT,
  customerId varchar (64) -- The cust_id is the external hotel id that would be pre-populated when the hotel client is on-boarded.
);

create table IF NOT EXISTS HOTEL_RESERVATION(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
 hotelId INTEGER,
 guestFirstName varchar(50),
 guestLastName varchar(50),
 guestEmail varchar(200),
 checkIn TIMESTAMP,
 checkOut TIMESTAMP
);


--TO-DO: Create FK