
drop table IF EXISTS HOTEL_CONFIG;

create table HOTEL_CONFIG (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  hotelName varchar(1000) not null,
  address varchar(4000) not null,
  city varchar (200) not null,
  state varchar (2) not null,
  country varchar (100) not null,
  zip varchar(10),
  roomCount INTEGER not null,
  overbookingLevel FLOAT not null,
  customerId varchar (64) not null -- The cust_id is the external hotel id that would be pre-populated when the hotel client is on-boarded.
);

drop table  IF EXISTS HOTEL_RESERVATION;

create table HOTEL_RESERVATION(
 id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
 hotelId INTEGER NOT NULL,
 guestFirstName varchar(50) not null,
 guestLastName varchar(50) not null,
 guestEmail varchar(200) not null,
 checkIn TIMESTAMP not null,
 checkOut TIMESTAMP not null
);
